-------------------------------------------------------------------------------
Test set: org.apache.hadoop.ozone.container.common.impl.TestContainerPersistence
-------------------------------------------------------------------------------
Tests run: 84, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.332 s <<< FAILURE! - in org.apache.hadoop.ozone.container.common.impl.TestContainerPersistence
TestContainerPersistence.testGetContainerReports  Time elapsed: 0.047 s  <<< ERROR!
org.apache.hadoop.hdds.scm.container.common.helpers.StorageContainerException: Container creation failed because ContainerFile already exists
	at org.apache.hadoop.ozone.container.keyvalue.KeyValueContainer.create(KeyValueContainer.java:191)
	at org.apache.hadoop.ozone.container.common.impl.TestContainerPersistence.addContainer(TestContainerPersistence.java:200)
	at org.apache.hadoop.ozone.container.common.impl.TestContainerPersistence.testGetContainerReports(TestContainerPersistence.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.hadoop.fs.FileAlreadyExistsException: container already exists on disk.
	at org.apache.hadoop.ozone.container.common.helpers.ContainerUtils.verifyIsNewContainer(ContainerUtils.java:126)
	at org.apache.hadoop.ozone.container.keyvalue.KeyValueContainer.create(KeyValueContainer.java:164)
	... 17 more

